import type { Metadata } from "next";
// import { Geist, Geist_Mono, Water_Brush } from "next/font/google";
import "./globals.css";
import { Header } from "./components/header/Header";
import { Footer } from "./components/footer/Footer";
import { DropDownMenu } from "./components/header/DropDownMenu";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="h-full flex flex-col">
        <Header />
        <div className="flex flex-col flex-1 font-sans dark:bg-black">
          <main className="flex-1 xl:mx-[5%] bg-[#e2e2e2] dark:bg-black sm:items-start">
            {children}
          </main>
        </div>
        <Footer />
      </body>
    </html>
  );
}
